### ISSUE TITLE
Timeout on file upload

### ISSUE THREAD

**Issue by fzlee** [tvrcgo/upload-to-oss#3]
It seems that default timeout for file upload is 60s, which works most of the time. 
But it doesn't for files bigger than 100MB, which will take more than 60s.
what's worse, it doesn't raise an error on timeout, github runner will show an "success" response 

```
(node:4437) UnhandledPromiseRejectionWarning: ResponseTimeoutError: Response timeout for 60000ms, PUT http://***.oss-cn-hangzhou.aliyuncs.com/release/***-electron/***-2.0.40-setup.exe -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":4,"createSocketErrorCount":0,"closeSocketCount":1,"errorSocketCount":0,"timeoutSocketCount":1,"requestCount":1,"freeSockets":{},"sockets":{"***.oss-cn-hangzhou.aliyuncs.com:80:":3},"requests":{}}, socketHandledRequests: 1, socketHandledResponses: 0)
```

**Comment by tvrcgo** [comment]
> It seems that default timeout for file upload is 60s, which works most of the time. But it doesn't for files bigger than 100MB, which will take more than 60s. what's worse, it doesn't raise an error on timeout, github runner will show an "success" response
> 
> ```
> (node:4437) UnhandledPromiseRejectionWarning: ResponseTimeoutError: Response timeout for 60000ms, PUT http://***.oss-cn-hangzhou.aliyuncs.com/release/***-electron/***-2.0.40-setup.exe -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":4,"createSocketErrorCount":0,"closeSocketCount":1,"errorSocketCount":0,"timeoutSocketCount":1,"requestCount":1,"freeSockets":{},"sockets":{"***.oss-cn-hangzhou.aliyuncs.com:80:":3},"requests":{}}, socketHandledRequests: 1, socketHandledResponses: 0)
> ```

- Set timeout 10min (d4e133a5162da2d935ad06f289fd0a1924d4790f)
- Raise oss error (dcc9972dba51e539cef89f52ec5217398c3471e8)
