### ISSUE TITLE
need to upload 3 files, but 1 file uploaded twice and another file didn't get uploaded

### ISSUE THREAD

**Issue by tigerinus** [tvrcgo/upload-to-oss#4]
你好，

我们的开源项目依赖你的 upload-to-oss 将构建好的包上传至阿里云 OSS。感谢你的开源！

目前遇到一个问题，发生了几次了。

简单讲我们每个项目针对 amd64, arm64, arm7 构建三个包，为了方便国内用户下载需要上传至 OSS。但是偶尔发现它会把把同一个包上传多次，而另外的包并没有上传。

比如

![b5a86965-bbd5-4e6c-aeae-4f62ae789e1e](https://user-images.githubusercontent.com/7172560/213510790-51677cfb-f4be-48c5-b99e-55bc561d4c5f.jpeg)
https://github.com/IceWhaleTech/CasaOS-CLI/actions/runs/3941671091/jobs/6744375998

我们检查过 workflow 脚本，貌似是没有问题的：

![b2157623-6d80-41f8-8b44-cfa089e31390](https://user-images.githubusercontent.com/7172560/213510893-3b6aba2d-cbb0-4b0f-a8cc-47afe9d3df84.jpeg)
https://github.com/IceWhaleTech/CasaOS-CLI/blob/main/.github/workflows/release.yml#L61-L63

麻烦你帮忙看一下谢谢！！

**Comment by tvrcgo** [comment]
怎么上传多次，同一个文件名？

**Comment by tigerinus** [comment]
> 怎么上传多次，同一个文件名？

你看一下第一个截图，它把同一个上传了两次

**Comment by tvrcgo** [comment]
> > 怎么上传多次，同一个文件名？
> 
> 你看一下第一个截图，它把同一个上传了两次

你仔细看第一个图，同一个两次是因为你的 workflow file 里面就是那么写的，你可以看你的 job 左下角的 workflow file

**Comment by tigerinus** [comment]
> 

Workflow 脚本里并没有重复的文件名。三个文件分别针对的是 amd64, arm64, arm7

**Comment by tvrcgo** [comment]
> > 
> 
> 
> 
> Workflow 脚本里并没有重复的文件名。三个文件分别针对的是 amd64, arm64, arm7

你仔细看看那个 job 运行时的 workflow file，不是指现在的最新状态，可能是你们有人改错了

**Comment by tigerinus** [comment]
原来如此。我看的太不仔细了。感谢！
