### ISSUE TITLE
显式设置timeout

### ISSUE THREAD

**Issue by jackalcooper** [tvrcgo/upload-to-oss#5]
现在上传大文件会挂掉
```
Error: Response timeout for 600000ms, please increase the timeout or use multipartDownload.
```

**Comment by tvrcgo** [comment]
可以支持

**Comment by tvrcgo** [comment]
> 现在上传大文件会挂掉
> 
> ```
> Error: Response timeout for 600000ms, please increase the timeout or use multipartDownload.
> ```

oss-action@master 已支持
